import pyautogui
import time
my_range = 47
time.sleep(6)
for i in range(my_range):
    time.sleep(1)
    pyautogui.press('down')
    time.sleep(1)
    pyautogui.press('left')
    pyautogui.hotkey('ctrl','left')
    pyautogui.hotkey('ctrl','c')
    pyautogui.hotkey('ctrl','right')
    pyautogui.hotkey('alt','tab')
    pyautogui.click(1204,230)
    pyautogui.click(591,181)
    pyautogui.hotkey('ctrl','a')
    pyautogui.hotkey('ctrl','v')
    pyautogui.press('enter')
    time.sleep(2)
    pyautogui.click(635,215)
    pyautogui.hotkey('alt','tab')
    time.sleep(1)
    pyautogui.hotkey('ctrl','c')
    time.sleep(1)
    pyautogui.press('right')
    time.sleep(1)
    pyautogui.hotkey('alt','tab')
    pyautogui.click(1204,230)
    pyautogui.click(665,672)
    pyautogui.hotkey('ctrl','a')
    pyautogui.hotkey('ctrl','v')
    pyautogui.click(535,195)
    time.sleep(3)
    pyautogui.hotkey('alt','tab')
